;
; Logging configuration for Kisan Mitra Asterisk
;

[general]
dateformat=%F %T
appendhostname=yes

[logfiles]
console => verbose,notice,warning,error
messages => notice,warning,error
full => debug,verbose,notice,warning,error,dtmf,fax

[syslog]
;local0 => NOTICE,WARNING,ERROR
